In [1]:
import numpy as np
 

In [2]:
a=np.eye(2)
b=np.ones((2,2))*2
b

array([[ 2.,  2.],
       [ 2.,  2.]])

In [8]:
a=np.array([[1,2],[1,1]])
a
b=np.array([[1,2],[1,1]])
c=np.array([3,4])


array([3, 4])

In [10]:
np.linalg.solve(a,c)

array([ 5., -1.])

In [15]:
2*np.eye(a.shape[0])

array([[ 2.,  0.],
       [ 0.,  2.]])

In [18]:
a[0,1]

2

In [20]:
np.linalg.inv(a)

array([[-1.,  2.],
       [ 1., -1.]])

In [22]:
np.sum(a[1,:])

2

In [23]:
a/2

array([[ 0.5,  1. ],
       [ 0.5,  0.5]])

In [46]:
a=np.random.randn(5,5)
a

array([[ 0.83704857, -1.85059185,  0.15674789, -0.01458978,  1.60638947],
       [ 0.55575542, -0.3521752 , -0.0639756 , -0.77570349,  0.5668511 ],
       [-2.29112169, -1.87515396, -0.95520417,  0.29805445,  0.68595676],
       [ 0.42217319, -1.23691491, -1.05130868, -0.19565186, -1.43566368],
       [ 0.59049256, -1.27122879,  0.84289023,  0.19361644,  0.89416149]])

In [37]:
 a[np.nonzero((a>0)&(a<1))]

array([ 0.91880769,  0.5640678 ,  0.27426728,  0.0997886 ,  0.72113788,
        0.87793024,  0.85646844,  0.68050528,  0.36169188,  0.46342121])

In [36]:
np.mean(np.nonzero((a>0)&(a<1)))

1.6000000000000001

In [48]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [49]:
np.linalg.eig(a)

(array([ 1.,  2.,  3.]), array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]]))

In [82]:
b[1][np.nonzero(x)]

array([[ 0.        ,  0.81649658,  0.81649658],
       [ 1.        , -0.40824829, -0.40824829]])

In [81]:
x=np.in1d(b[0],np.sort(b[0])[:2])

In [77]:
a=np.array([[-1,1,0],
       [-4,3,0],
       [1,0,2]])
b=np.linalg.eig(a)
b[0]
b[1]

array([[ 0.        ,  0.40824829,  0.40824829],
       [ 0.        ,  0.81649658,  0.81649658],
       [ 1.        , -0.40824829, -0.40824829]])