In [1]:
from numpy import *
import numpy as np
X=np.load("mnist_train_images.npy")
Y=np.load("mnist_train_labels.npy")



In [15]:
a=ones([1,5])
b=repeat(a,3)
c=b.reshape([3,5])


In [16]:
c.shape[1]

5

In [2]:
from numpy import random
W1=random.uniform(-1/sqrt(784),1/sqrt(784),size=(784,30))
W2=random.uniform(-1/sqrt(30),1/sqrt(30),size=(30,10))
b1=0.01*ones([55000,30])
b2=0.01*ones([55000,10])

In [4]:

z1=np.dot(X,W1)+b1
h1=where(z1<0,0,z1)
z2=np.dot(h1,W2)+b2
f=exp(z2)
y_hat=f/f.sum(axis=1)[:,None]


In [5]:
sum(diag(np.dot(W1.T,W1)))

10.030831990315976

In [6]:
grad_M2=np.dot(h1.T,(y_hat-Y))

In [5]:
gt=np.dot((y_hat-Y),W2.T)*sign(z1)
m=gt.shape[0]
n=gt.shape[1]
g=zeros([55000,784*30])
for i in range(0,55000):
    for j in range(0,30):
        g[i,784*j:784*(j+1)]=gt[i,j]*X[i,:]
   

In [9]:
np.dot((y_hat-Y),W2.T).shape

(55000, 30)

In [8]:
z1.shape

(55000, 30)

In [58]:
g2=np.sum(g,axis=0)


In [59]:
grad_M1=zeros([30,784])
for i in range(0,30):
    for j in range(0,784):
        grad_M1[i,j]=g2[784*i+j]


array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [ ]:
    def SGD(self, training_data, epochs, mini_batch_size, eta,
            test_data=None):


        if test_data: n_test = len(test_data)
        n = len(training_data)
        for j in xrange(epochs):
            random.shuffle(training_data)
            mini_batches = [
                training_data[k:k+mini_batch_size]
                for k in xrange(0, n, mini_batch_size)]
            for mini_batch in mini_batches:
                self.update_mini_batch(mini_batch, eta)
            if test_data:
                print "Epoch {0}: {1} / {2}".format(
                    j, self.evaluate(test_data), n_test)
            else:
                print "Epoch {0} complete".format(j)

In [97]:
training_data=np.hstack([X,Y])
random.shuffle(training_data)
a=training_data[:,:784]
b=training_data[:,-10:]
b.shape

(55000, 10)

In [93]:
  mini_batches = [
                training_data[k:k+550,:]
                for k in range(0, 55000, 550)]

In [95]:
Y.shape

(55000, 10)

In [ ]:
grad_W1=zeros([784,30])
for j in range(0,n):    
    grad[j]=grad[i,:]+grad[i,j]
    grad_W1= 

In [39]:
a=random.uniform(-1,1,size=6)
a

array([ 0.01761677,  0.41037645,  0.48785226, -0.50533703, -0.01230604,
       -0.69197062])

In [40]:
sign(a)

array([ 1.,  1.,  1., -1., -1., -1.])

In [25]:




def J (w, faces, labels):
    f=exp(np.dot(faces,w))
    y_hat=f/f.sum(axis=1)[:,None]
    m=labels.shape[0]
    Jsum=0
    for i in range(0,m):
        Jsum=Jsum+np.dot(labels[i,:].T,log(y_hat[i,:]))
    J=-1/m*Jsum
    return J  

def gradJ (w, faces, labels):
    f=exp(np.dot(faces,w))
    y_hat=f/f.sum(axis=1)[:,None]
    gradJ=np.dot(faces.T,(y_hat-labels))
    return gradJ 

In [4]:
    w=np.zeros((784,10)) # Or set to random vector
    J_dif=1
    cost=[]
    n=0
    while J_dif > 0.001:
        J0=J (w, trainingX, trainingY)
        Des_gradJ=gradJ (w, trainingX, trainingY)
        w=w-0.000002*Des_gradJ
        J1=J (w, trainingX, trainingY)
        J_dif=J0-J1
        cost.append(J1)
    cost
    w

    


array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [27]:
myList=cost[-20:]
b=['%.4f' %elem for elem in myList]
print("Training cost:{} ".format(b) )
 

Training cost:['0.5396', '0.5384', '0.5371', '0.5359', '0.5348', '0.5336', '0.5324', '0.5313', '0.5302', '0.5291', '0.5280', '0.5269', '0.5258', '0.5247', '0.5237', '0.5227', '0.5216', '0.5206', '0.5196', '0.5186'] 


In [46]:
 
f=exp(np.dot(testingX,w))
y_hat=f/f.sum(axis=1)[:,None]


In [33]:
y_hat.argmax(axis=1)

array([7, 2, 1, ..., 4, 8, 6], dtype=int64)

In [47]:
f=exp(np.dot(testingX,w))
y_hat=f/f.sum(axis=1)[:,None]
m=testingY.shape[0]
n=0
for i in range(0,m):
    for j in range(0,10):
        if (y_hat[i,j]==np.sort(y_hat[i,:])[-1]):
            y_hat[i,j]=1
        else:
            y_hat[i,j]=0   
                                  
    if (y_hat[i,:]==testingY[i,:]).all():
        n=n+1
a=round(n/m,4)
print("The accuracy on the testing set: {}".format(a))

The accuracy on the testing set: 0.8816
